### ISSUE TITLE
Buzz on ROS

### ISSUE THREAD

**Issue by TSC21** [MISTLab/Buzz#11]
Hi there! Really neat and interesting API you have created. Congrats!
...But I'm a ROS/gazebo user and what I pretende to know is if there are plans to create a ROS package of it? It would be of great use for most of ROS community.

Thanks and once again congrats for this great piece of work.

**Comment by ilpincy** [comment]
Hi!

Thanks for your interest in Buzz! :-)

We designed Buzz to be an extension language for the precise purpose of integrating it with other systems, and ROS was indeed one of the first we thought about.

So yes, we have plans to integrate ROS and Buzz. It won't happen right now, as we're pretty busy tidying up the code and setting up a dedicated website. As soon as we're done with that, we'll look into integration.

We would be happy to have ROS/Gazebo enthusiasts on board in the process. So, if you feel like collaborating, let us know!

Cheers,
Carlo

**Comment by TSC21** [comment]
You can count on me then :)

**Comment by gergia** [comment]
Also interested in this topic and would like to help (although, I am a beginner in ROS so I don't feel I could do it on my own).

**Comment by ilpincy** [comment]
I'm writing more docs on the [wiki](http://the.swarming.buzz/wiki/doku.php). In particular, next week I'll write a page that explains how to interface Buzz with any C/C++ program. If anybody is interested in using that info to integrate Buzz with ROS, let me know. I have some ideas on how to do it, but if anybody is up for suggestions, feel free to write to me.

**Comment by TSC21** [comment]
@ilpincy I'm really interested on your thoughts and maybe we can discuss something by skype or gitter.

**Comment by ilpincy** [comment]
Sure thing! I finally got back to working on Buzz, and I'm considering to proceed with the integration. I was thinking about adding a Buzz node into ROS, which would interoperate with the rest of the ROS node network.

The way I see it, the most comfortable way to proceed would be to have a basic BuzzROS node, which people could extend to add extra functionality. The basic functionality would be a set of methods to launch the VM, set the bytecode, report errors; and a set of methods to make integration of new message types easy and fast.

I'm currently looking into how to organize all this. If you have ideas, let me know!

**Comment by TSC21** [comment]
@ilpincy what is the current status of this? Do you have updates? Maybe something we can sync?

**Comment by beltrame** [comment]
You can take a look at github.com/MISTLab/ROSBuzz to see the current status of development. We are currently refactoring it for a first release. What you see in the repo was tested on the Matrice M100, 3DR Solo, and Clearpath Husky. Caveat: it's still experimental, if you want to play safe you should wait for the first release, which should happen at ROSCon this year.

**Comment by TSC21** [comment]
Oh great! And you are using MAVROS :D (I'm one of the maintainers of it btw). I will for sure try this. The best way I'm thinking right now is try it with the SITL Gazebo sim. Will let you know of my findings then. Maybe we can sync on MAVROS side to direct support of your msgs?

**Comment by dastoqc** [comment]
Hi.

Sorry for the late reply. I'm the among the main maintainers of ROSBuzz. Yes, we selected mavros to ensure we comply to a widely used standard. We deployed it on many UAVs and Rovers already seemlessly thanks to that. I also have a Gazebo setup working to use many instances of ROSBuzz with a custom flight controller. We are currently testing PX4 SITL. We should discuss this further by email. Really great that we have trigerred your interest!

**Comment by TSC21** [comment]
@dastoqc even greater that MAVROS serves the purpose as an interface for you to test Buzz!! I'm currently developing on PX4 and PX4 SITL also so it could be awesome that we can sync efforts. I Buzz itself can become one standard for drone platforms that use Mavlink, so probably we can sync efforts so we can have the community also contributing and testing the framework. My e-mail is n<dot>marques21<at>hotmail<dot>com. Please let's sync up there and maybe we can discuss approaches on how to bring this to the mainstream.

**Comment by ilpincy** [comment]
I love the direction this discussion has taken :-) Keep me in the loop, I'm happy to help!

**Comment by TSC21** [comment]
@ilpincy perfect. Can you please sync up by email also?

**Comment by ilpincy** [comment]
Sure, how do I do that?

**Comment by TSC21** [comment]
Send me an email with the current status, goals, and if you can share some examples would be great. That way I can also see if we can have base integration for Buzz on MAVROS by default. Then we can also discuss some more projects if you want.

**Comment by ilpincy** [comment]
OK, I'll do it next week after RSS!

**Comment by TSC21** [comment]
> OK, I'll do it next week after RSS!

Thanks!

**Comment by TSC21** [comment]
@ilpincy am I still getting that e-mail? :)

**Comment by ilpincy** [comment]
I got a little carried away :-) Well, @dastoqc is the main developer of this part of the work. I'd suggest him to give us an update. I know he and a few students have worked on this, but I'm not aware of the current status of the project.

**Comment by dastoqc** [comment]
Well the integration of Buzz in a ROS (1) node is completed since a year or so : https://github.com/MISTLab/ROSBuzz. We have not released the Gazebo simulator packages and environment yet because... well, time. While we deployed this node on Husky rovers, DJI M100, 3DR Solo and Intel Aero in field tests, we currently only focus our simulation work on the M100. You can get more informations here: https://arxiv.org/pdf/1710.08843.pdf.

**Comment by aarushi0107** [comment]
Hello there,
I am getting the following error on running the command roslaunch rosbuzz rosbuzz.launch

RLException: [rosbuzz.launch] is neither a launch file in package [rosbuzz] nor is [rosbuzz] a launch file name
The traceback for the exception was written to the log file

**Comment by dastoqc** [comment]
Hi.

I would be happy to help. If you have an issue with ROSBuzz, please raise it on the proper repository: https://github.com/MISTLab/ROSBuzz.

First guess: have you sourced you local ROS workspace after compiling and before trying to launch the node (source devel/setup.bash) ?

Best,
David.

**Comment by aarushi0107** [comment]
It is showing that there is no such file or repository on sourcing my local ROS workspace

**Comment by ilpincy** [comment]
Please move this discussion to the ROSBuzz repository, here it is misplaced.
