### ISSUE TITLE
Encounter mistakes when use table in communication

### ISSUE THREAD

**Issue by dbtx123** [MISTLab/Buzz#13]
When use functions 
_neighbors.broadcast("key", sendTable)_ 
and _neighbors.listen("key", function(vid, recvTable, rid) { })_ 
to communicate, if _sendTable_ and _recvTable_ are defined as tables, and several _recvTables_ are stored in another map, such as _messageStorage_, fail to fetch the right value of _recvTable_ in _messageStorage_.
Sample source codes are provided in attached file, with _testbzzDesired.bzz_ and _testbzzDesired.argos_ showing the desired result, and _testbzz.bzz_ and _testbzz.argos_ showing the actual result.
[bzzIssue.zip](https://github.com/MISTLab/Buzz/files/605162/bzzIssue.zip)

**Comment by ilpincy** [comment]
Can you please be more specific? The code you sent me forces me to guess a little too much. What do you mean by:

> fail to fetch the right value of recvTable in messageStorage

What do you expect to see, and what do you see instead?

In the code that you provide in testbuzz.bzz, the following lines overwrite the same message over and over:

```
neighbors.listen("message",
  function(vid,value,rid){
    #store the received message
    m_messageRecv.ID=value.ID
    #add the received message
    m_messageStorage[m_messageCunt]=m_messageRecv
    m_messageCunt=m_messageCunt+1
  })
```

at the end, what you should see is that every element of `m_messageStorage` is the same.

**Comment by dbtx123** [comment]
Sorry for fail to describe the issue clearly.
I intend to save messages received from different neighbours as elements of _m_messageStorage_, so once the _neighbors.listen()_ function is called, the received _value_ should be saved as an element in _m_messageStorage_,which means the elements in _m_messageStorage_ should be different. But it seems they are overwrite somewhere as you mentioned, and all the elements become the same. 
When I exchange the _m_messageRecv_ to _value_ in the following line:
m_messageStorage[m_messageCunt]=m_messageRecv   (1)
every thing works as I expected. 
It seems that the problem is about the table _m_messageRecv_, which is used to save the received message for temporary and should be equal to _value_. So the outcome should be the same no matter I use _m_messageRecv_ or  _value_ in (1).  But the fact is when I use _m_messageRecv_, every element in _m_messageStorage_ is overwritten, and I don't know why.

**Comment by ilpincy** [comment]
This is not a bug, it's just the way tables work in Buzz. Tables are
handled by reference, not by value. The behavior you see is correct.

If you want to deep copy a table, you have to do it like in the second code
example you show.

**Comment by dbtx123** [comment]
I see. Thank you very much for answering my question!
