### ISSUE TITLE
Virtual Stigmergy conflict resolver segfault

### ISSUE THREAD

**Issue by vivek-shankar** [MISTLab/Buzz#62]
The conflict resolver of Virtual Stigmergy(VS) seems to crash with a Segmentation Fault. 
It used to work with the older version of Buzz + Argos. 
The latest version of Buzz + ARGOS causes a segmentation fault when a conflict resolver lambda function is called, in the result of a conflict. There is also an invalid free during the initialization part.  I am attaching a minimalistic buzz script that leads to a Memory leak and the leak summary from Valgrind. 
[VS_Bug.txt](https://github.com/MISTLab/Buzz/files/1744980/VS_Bug.txt)
[leak_summery.txt](https://github.com/MISTLab/Buzz/files/1744988/leak_summery.txt)

**Comment by vivek-shankar** [comment]
Thank you Carlo for the fix.

**Comment by MajdaMoussa** [comment]
I got the same segmentation fault problem when trying to run the same code on Khepera robots. I think the problem comes this time from BuzzKH4... What do you think?

**Comment by ilpincy** [comment]
If you got the same problem, probably it's because you didn't update the Buzz VM on the khepera. Otherwise, there's a bug in the BuzzKH4 code, and it should be reported there.
