### ISSUE TITLE
online resources to build a community

### ISSUE THREAD

**Issue by robinpaulson** [MISTLab/Buzz#9]
This software fascinates me greatly and it would be very useful to have a community around that software. Perhaps it could be based around the traditional resources of a mailing list, forum and/or wiki where we could discuss the software, get help on problems, show off examples and so on. Is there anything like this existing or do you have plans to build something? Github has a certain community aspect, but dedicated tools would be very useful.

Cheers,

Robin

**Comment by ilpincy** [comment]
Dear Robin,

Thanks a lot for your interest! We do have plans on building a community around Buzz. The ultimate objective of our work is to make a platform that would enable people to share and reuse swarm algorithms, more or less in the style of what today is done with ROS.

We are a little overwhelmed by the instant attention this work has received, but we're very happy that people are expressing interest. That's the whole point of our effort!

So, to get to the point: the plans are indeed to create a dedicated wiki page with forum and mailing list, outside of GitHub. These platforms would be used to allow contributors to improve Buzz itself, provide examples/tutorials, and share code.

In the next weeks you'll see lots of things being added. If you have feedback or want to contribute, do feel free to contact us.

Thanks again for your interest! :-)

Cheers,
Carlo

**Comment by ilpincy** [comment]
The website is at http://the.swarming.buzz/ and we are currently adding more!
